version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-sam-python-tochiji-2022"
s3_bucket = "test-sam-python-tochiji-2022"
s3_prefix = "test-sam-python"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
